<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http:///model.ecore" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="BookingActivity"/>
  <eClassifiers xsi:type="ecore:EClass" name="showRoomOccupancy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="u" ordered="false" lowerBound="1"
        eType="#//HotelService/HotelReceptionist"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rm" ordered="false" lowerBound="1"
        eType="#//HotelService/IRoomManager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckInSuccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="r" ordered="false" lowerBound="1"
        eType="ecore:EClass HotelSystem.ecore#//Reservation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="k" ordered="false" lowerBound="1"
        eType="#//KeyCardService/KeyCardsProvides"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" ordered="false"
        lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Customer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" ordered="false"
        lowerBound="1" eType="#//HotelService/HotelReceptionist"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bm" ordered="false" lowerBound="1"
        eType="#//HotelService/IBookingManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" ordered="false" lowerBound="1"
        eType="ecore:EClass HotelSystem.ecore#//Booking"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="reserveARoom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="r" ordered="false" lowerBound="1"
        eType="#//HotelService/HotelReceptionist"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservation" ordered="false"
        lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Reservation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booking" ordered="false"
        lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Booking"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roomManager" ordered="false"
        lowerBound="1" eType="#//HotelService/IRoomManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reservationManager" ordered="false"
        lowerBound="1" eType="#//HotelService/IReservationManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookingManager" ordered="false"
        lowerBound="1" eType="#//HotelService/IBookingManager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="makeABooking">
    <eStructuralFeatures xsi:type="ecore:EReference" name="r" ordered="false" lowerBound="1"
        eType="#//HotelService/HotelReceptionist"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" ordered="false" lowerBound="1"
        eType="ecore:EClass HotelSystem.ecore#//Booking"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="c" ordered="false" lowerBound="1"
        eType="ecore:EClass HotelSystem.ecore#//Customer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pd" ordered="false" lowerBound="1"
        eType="ecore:EClass HotelSystem.ecore#//PaymentDetails"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bank" ordered="false" lowerBound="1"
        eType="#//BankingService/CustomerProvides"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bm" ordered="false" lowerBound="1"
        eType="#//HotelService/IBookingManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cm" ordered="false" lowerBound="1"
        eType="#//HotelService/ICustomerManager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="checkOutSuccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" ordered="false"
        lowerBound="1" eType="#//HotelService/HotelReceptionist"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyCards" ordered="false"
        lowerBound="1" eType="#//KeyCardService/KeyCardsProvides"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="r" ordered="false" lowerBound="1"
        eType="ecore:EClass HotelSystem.ecore#//Reservation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="b" ordered="false" lowerBound="1"
        eType="ecore:EClass HotelSystem.ecore#//Booking"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bank" ordered="false" lowerBound="1"
        eType="#//BankingService/CustomerProvides"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="c" ordered="false" lowerBound="1"
        eType="ecore:EClass HotelSystem.ecore#//Customer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rm" ordered="false" lowerBound="1"
        eType="#//HotelService/IReservationManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bm" ordered="false" lowerBound="1"
        eType="#//HotelService/IBookingManager"/>
  </eClassifiers>
  <eSubpackages name="BankingService" nsURI="http:///model/BankingService.ecore" nsPrefix="model.BankingService">
    <eClassifiers xsi:type="ecore:EClass" name="AdministratorProvides" abstract="true"
        interface="true">
      <eOperations name="makeDeposit" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="sum" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eOperations name="addCreditCard" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="removeCreditCard" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="getBalance" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomerProvides" abstract="true"
        interface="true">
      <eOperations name="makePayment" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="sum" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
      <eOperations name="isCreditCardValid" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccv" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expiryMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expiryYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BankComponent"/>
  </eSubpackages>
  <eSubpackages name="KeyCardService" nsURI="http:///model/KeyCardService.ecore" nsPrefix="model.KeyCardService">
    <eClassifiers xsi:type="ecore:EClass" name="KeyCards"/>
    <eClassifiers xsi:type="ecore:EClass" name="KeyCardsProvides" abstract="true"
        interface="true">
      <eOperations name="returnedCards" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eParameters name="reservation" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="assignCardsToReservation" ordered="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eParameters name="reservation" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eParameters name="numberOfCards" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="HotelService" nsURI="http:///model/HotelService.ecore" nsPrefix="model.HotelService">
    <eClassifiers xsi:type="ecore:EClass" name="HotelReceptionist"/>
    <eClassifiers xsi:type="ecore:EClass" name="IRoomManager" abstract="true" interface="true">
      <eOperations name="getAvailableRooms" ordered="false" upperBound="-1" eType="ecore:EClass HotelSystem.ecore#//Room">
        <eParameters name="fromDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="toDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="roomTypeIds" ordered="false" upperBound="-1" eType="ecore:EClass HotelSystem.ecore#//RoomType"/>
      </eOperations>
      <eOperations name="getRoomOccupancy" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eParameters name="fromDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="toDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IBookingManager" abstract="true" interface="true">
      <eOperations name="createBooking" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Booking"/>
      <eOperations name="getBookingByNumber" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Booking">
        <eParameters name="bookingId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="deleteBooking" ordered="false" lowerBound="1">
        <eParameters name="booking" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Booking"/>
      </eOperations>
      <eOperations name="getBookingsByCustomer" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
        <eParameters name="customer" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Customer"/>
      </eOperations>
      <eOperations name="setBookingCustomer" ordered="false" lowerBound="1">
        <eParameters name="booking" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Booking"/>
        <eParameters name="customer" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Customer"/>
      </eOperations>
      <eOperations name="isBillPaidInFull" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="booking" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Booking"/>
      </eOperations>
      <eOperations name="getBill" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Bill">
        <eParameters name="booking" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Booking"/>
      </eOperations>
      <eOperations name="getBookingByReservation" ordered="false" lowerBound="1">
        <eParameters name="reservation" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Reservation"/>
        <eParameters name="booking" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Booking"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IReservationManager" abstract="true"
        interface="true">
      <eOperations name="createReservation" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="booking" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Booking"/>
        <eParameters name="fromDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="toDate" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eParameters name="roomId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
        <eParameters name="costCategoryId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="getReservation" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Reservation">
        <eParameters name="reservationId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="getNonCheckedInReservation" ordered="false" upperBound="-1"
          eType="ecore:EClass HotelSystem.ecore#//Reservation">
        <eParameters name="booking" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Booking"/>
      </eOperations>
      <eOperations name="checkInReservation" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="reservationId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="checkOutReservation" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="reservation" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Reservation"/>
      </eOperations>
      <eOperations name="getCurrentReservationByRoomNumber" ordered="false" lowerBound="1"
          eType="ecore:EClass HotelSystem.ecore#//Reservation">
        <eParameters name="roomNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HotelManager"/>
    <eClassifiers xsi:type="ecore:EClass" name="HotelManagerProvides" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="HotelStaff"/>
    <eClassifiers xsi:type="ecore:EClass" name="HotelStaffProvides" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IRoomTypeManager" abstract="true"
        interface="true">
      <eOperations name="getRoomTypes" ordered="false" upperBound="-1" eType="ecore:EClass HotelSystem.ecore#//RoomType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ICustomerManager" abstract="true"
        interface="true">
      <eOperations name="getCustomerByIdNumber" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
        <eParameters name="idNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="getCustomersByName" ordered="false" upperBound="-1" eType="ecore:EClass HotelSystem.ecore#//Customer">
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="getCustomer" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Customer">
        <eParameters name="customerId" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
      </eOperations>
      <eOperations name="createCustomer" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Customer">
        <eParameters name="idNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
      </eOperations>
      <eOperations name="setPaymentDetailsForCustomer" ordered="false" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
        <eParameters name="customerId" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Customer"/>
        <eParameters name="firstName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="lastName" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="ccvNumber" ordered="false" lowerBound="1" eType="ecore:EDataType types.ecore#//String"/>
        <eParameters name="expireMonth" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eParameters name="expireYear" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="getPaymentDetailsByCustomer" ordered="false" lowerBound="1"
          eType="ecore:EClass HotelSystem.ecore#//PaymentDetails">
        <eParameters name="customerId" ordered="false" lowerBound="1" eType="ecore:EClass HotelSystem.ecore#//Customer"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
